app: yolo-bouldering

service: yolo-bouldering-sns

provider:
  name: aws
  runtime: nodejs12.x
  stage: dev
  region: ap-southeast-1
  memorySize: 1024
  environment:
    BOT_TOKEN: ${file(../serverless-config.${self:custom.stage}.json):BOT_TOKEN, ''}
    BOT_CHAT_ID: ${file(../serverless-config.${self:custom.stage}.json):BOT_CHAT_ID, ''}
  logRetentionInDays: 30
  lambdaHashingVersion: 20201221

plugins:
  - serverless-plugin-typescript

functions:
  telegramDispatcher:
    handler: src/telegramDispatcher.handler
    events:
      - sns:
          arn:
            Ref: TelegramSNS
          topicName: '${self:service}-${self:custom.stage}-telegram'

resources:
  Resources:
    TelegramSNS:
      Type: AWS::SNS::Topic
      Properties:
        TopicName: '${self:service}-${self:custom.stage}-telegram'

    SSMParameterTelegramSNSArn:
      Type: AWS::SSM::Parameter
      Properties:
        Name: /${self:custom.stage}/sns/telegram/arn
        Type: String
        Value:
          Ref: TelegramSNS
        Tags:
          Environment: ${self:custom.stage}

custom:
  stage: ${opt:stage, self:provider.stage}
