app: yolo-bouldering

service: yolo-bouldering-predictor

provider:
  name: aws
  stage: dev
  runtime: python3.7
  region: ap-southeast-1
  memorySize: 2048
  apiGateway:
    # Required for binary media such as images to work with api gateway
    binaryMediaTypes:
      - 'multipart/form-data'
  logRetentionInDays: 7
  lambdaHashingVersion: 20201221
  environment:
    PYTHON_ENV: ${self:custom.stage}
    ALLOWED_ORIGIN: ${self:custom._origin.${self:custom.stage}}

functions:
  PredictImage:
    handler: handler.predict
    timeout: 10
    events:
      - http:
          path: /v1/predict
          method: post
          cors:
            origin: ${self:custom._origin.${self:custom.stage}}
            headers: '*'
            methods:
              - POST
              - OPTIONS

custom:
  stage: ${opt:stage, self:provider.stage}

  # Compile non-pure python modules on non-linux OSs via Docker
  pythonRequirements:
    dockerizePip: true

  apiGatewayThrottling:
    maxRequestsPerSecond: ${self:custom._maxRequestsPerSecond.${self:custom.stage}}
    maxConcurrentRequests: ${self:custom._maxConcurrentRequests.${self:custom.stage}}
  _maxRequestsPerSecond:
    dev: 1
    prod: 3
  _maxConcurrentRequests:
    dev: 1
    prod: 3
  _origin:
    dev: '*'
    prod: '*'

plugins:
  - serverless-python-requirements
  - serverless-api-gateway-throttling

package:
  patterns:
    - '!node_modules/**'
