app: yolo-bouldering

service: yolo-bouldering-user

provider:
  name: aws
  runtime: nodejs12.x
  stage: dev
  region: ap-southeast-1
  memorySize: 1024
  environment:
    NODE_ENV: ${self:custom.stage}
    ALLOWED_ORIGIN: ${self:custom._origin.${self:custom.stage}}
    COGNITO_CLIENT_ID: ${self:custom.cognitoClientId}
    COGNITO_USERPOOL_ID: ${self:custom.cognitoUserpoolId}
  logRetentionInDays: 30
  lambdaHashingVersion: 20201221
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - cognito-idp:SignUp
            - cognito-idp:ConfirmSignUp
            - cognito-idp:InitiateAuth
          Resource: ${self:custom.cognitoArn}
        - Effect: Allow
          Action:
            - cognito-idp:AdminGetUser
          Resource: ${self:custom.cognitoArn}

plugins:
  - serverless-plugin-typescript
  - serverless-api-gateway-throttling

functions:
  signup:
    handler: src/signup.handler
    events:
      - http:
          path: user/signup
          method: post
          cors:
            origin: ${self:custom._origin.${self:custom.stage}}

  confirmSignup:
    handler: src/confirmSignup.handler
    events:
      - http:
          path: user/confirm
          method: post
          cors:
            origin: ${self:custom._origin.${self:custom.stage}}

  resendCode:
    handler: src/resendCode.handler
    events:
      - http:
          path: user/resendCode
          method: post
          cors:
            origin: ${self:custom._origin.${self:custom.stage}}

  login:
    handler: src/login.handler
    events:
      - http:
          path: user/login
          method: post
          cors:
            origin: ${self:custom._origin.${self:custom.stage}}

  refreshToken:
    handler: src/refreshToken.handler
    events:
      - http:
          path: user/refreshToken
          method: post
          cors:
            origin: ${self:custom._origin.${self:custom.stage}}

  forgotPassword:
    handler: src/forgotPassword.handler
    events:
      - http:
          path: user/forgotPassword
          method: post
          cors:
            origin: ${self:custom._origin.${self:custom.stage}}

  confirmForgotPassword:
    handler: src/confirmForgotPassword.handler
    events:
      - http:
          path: user/resetPassword
          method: post
          cors:
            origin: ${self:custom._origin.${self:custom.stage}}

  logout:
    handler: src/logout.handler
    events:
      - http:
          path: user/logout
          method: post
          cors:
            origin: ${self:custom._origin.${self:custom.stage}}
          authorizer:
            arn: ${self:custom.cognitoArn}
            scopes:
              - aws.cognito.signin.user.admin

  deleteUser:
    handler: src/deleteUser.handler
    events:
      - http:
          path: user/delete
          method: delete
          cors:
            origin: ${self:custom._origin.${self:custom.stage}}
          authorizer:
            arn: ${self:custom.cognitoArn}
            scopes:
              - aws.cognito.signin.user.admin

custom:
  stage: ${opt:stage, self:provider.stage}
  cognitoArn: ${ssm:/${self:custom.stage}/cognito/arn}
  cognitoClientId: ${ssm:/${self:custom.stage}/cognito/clientId}
  cognitoUserpoolId: ${ssm:/${self:custom.stage}/cognito/poolId}
  apiGatewayThrottling:
    maxRequestsPerSecond: ${self:custom._maxRequestsPerSecond.${self:custom.stage}}
    maxConcurrentRequests: ${self:custom._maxConcurrentRequests.${self:custom.stage}}

  _maxRequestsPerSecond:
    dev: 1
    prod: 3
  _maxConcurrentRequests:
    dev: 1
    prod: 3
  _origin:
    dev: '*'
    prod: '*'
