app: yolo-bouldering

service: yolo-bouldering-user-cognito

provider:
  name: aws
  stage: dev
  region: us-east-1
  # iamRoleStatements:
    # - Effect: "Allow"
    #   Principal:
    #     Service: cognito-idp.amazonaws.com
    #   Action:
    #    - ses:SendEmail
    #    - ses:SendRawEmail
    #   Resource: <arn:email>

resources:
  Resources:
    CognitoUserPool:
      Type: AWS::Cognito::UserPool
      Properties:
        UserPoolName: ${self:service}-${self:provider.stage}-user-pool
        UsernameAttributes:
          - email
        AutoVerifiedAttributes:
          - email
        Policies:
          PasswordPolicy:
            MinimumLength: 8
        EmailConfiguration:
          EmailSendingAccount: COGNITO_DEFAULT
          # Ensure SourceArn is in us-east-1
          # Ensure SES has AWS production access
          # EmailSendingAccount: DEVELOPER
          # SourceArn: <arn:email>

custom:
  stage: ${opt:stage, self:provider.stage}
