[versions]
agp = "9.3.0"
javaToolchain = "25"
javaBytecode = "17"
androidCompileSdk = "36"
androidMinSdk = "24"
androidTargetSdk = "36"
lynx = "4.0.0"
appcompat = "1.7.1"
fresco = "2.3.0"


[libraries]
androidx-appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
lynx = { group = "org.lynxsdk.lynx", name = "lynx", version.ref = "lynx" }
lynx-service-http = { group = "org.lynxsdk.lynx", name = "lynx-service-http", version.ref = "lynx" }
lynx-service-image = { group = "org.lynxsdk.lynx", name = "lynx-service-image", version.ref = "lynx" }
lynx-service-log = { group = "org.lynxsdk.lynx", name = "lynx-service-log", version.ref = "lynx" }
lynx-xelement-input = { group = "org.lynxsdk.lynx", name = "xelement-input", version.ref = "lynx" }
lynx-xelement-svg = { group = "org.lynxsdk.lynx", name = "xelement-svg", version.ref = "lynx" }

fresco = { group = "com.facebook.fresco", name = "fresco", version.ref = "fresco" }


[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
