[versions]
agp = "9.3.0"
javaToolchain = "25"
javaBytecode = "17"
androidCompileSdk = "36"
androidMinSdk = "24"
androidTargetSdk = "36"
sparkling = "2.0.1"
appcompat = "1.6.1"
fresco = "2.3.0"


[libraries]
androidx-appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
sparkling = { group = "com.tiktok.sparkling", name = "sparkling", version.ref = "sparkling" }

fresco = { group = "com.facebook.fresco", name = "fresco", version.ref = "fresco" }
fresco-animated-gif = { group = "com.facebook.fresco", name = "animated-gif", version.ref = "fresco" }
fresco-animated-webp = { group = "com.facebook.fresco", name = "animated-webp", version.ref = "fresco" }


[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
