name: Build and Deploy

on: workflow_dispatch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@master

      - name: setup node
        uses: actions/setup-node@v1
        with:
          node-version: '14.x'

      - name: Configure AWS Credential
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-southeast-1

      - name: build
        working-directory: ./ionic_user_interface
        run: |
          npm ci
          npm run build
        env:
          VUE_APP_PREDICT_ENDPOINT_URL: ${{ secrets.VUE_APP_PREDICT_ENDPOINT_URL }}
          VUE_APP_USER_ENDPOINT_URL: ${{ secrets.VUE_APP_USER_ENDPOINT_URL }}
          VUE_APP_ROUTE_ENDPOINT_URL: ${{ secrets.VUE_APP_ROUTE_ENDPOINT_URL }}
          VUE_APP_MAP_EMBED_API: ${{ secrets.VUE_APP_MAP_EMBED_API }}
          VUE_APP_MAPBOX_ACCESS_KEY: ${{ secrets.VUE_APP_MAPBOX_ACCESS_KEY }}
          VUE_APP_TRACKING_ID: ${{ secrets.VUE_APP_TRACKING_ID }}
          VUE_APP_PRODUCTION_ROUTE: /

      - name: Copy files to S3
        working-directory: ./ionic_user_interface
        run: |
          aws s3 sync dist/ s3://${{ secrets.AWS_S3_CONTENT_BUCKET }}

      - name: Create Cloudfront invalidation
        working-directory: ./ionic_user_interface
        run: |
          aws cloudfront create-invalidation --distribution-id ${{ secrets.AWS_CLOUDFRONT_ID }} --paths "/*"
